apiVersion: apps/v1
kind: Deployment
metadata:
  name: xileok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xileok
  template:
    metadata:
      labels:
        app: xileok
    spec:
      containers:
      - image: okteto.dev/xileok:latest
        name: xileok
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b3c15112-5515-408a-9103-aa217ff6b57e"
        - name: Vless_Path
          value: "/vl1011"
        - name: Vmess_UUID
          value: "b3c15112-5515-408a-9103-aa217ff6b57e"
        - name: Vmess_Path
          value: "/vm2022"
        - name: Share_Path
          value: "/v2link"
